"""Mermaid rendering of the learned HA-ViD procedure knowledge (``docs/sop_knowledge.md``).

The diagrams are generated from the JSON files the checks read (``load_knowledge``), never drawn
by hand, so the documentation cannot describe knowledge the code does not use:
``tests/test_sop_mermaid.py`` fails when the committed page differs from a fresh rendering.
"""

from __future__ import annotations

import re
from collections.abc import Iterable, Mapping
from pathlib import Path

from sop_monitor.havid_sop import PLATES, load_knowledge
from sop_monitor.sop_graph import DurationBounds, TaskGraph

CLASSES = (
    "    classDef step fill:#eef2f7,stroke:#5a6b80,stroke-width:1.5px,color:#111",
    "    classDef mandatory fill:#fde7c8,stroke:#b35c00,stroke-width:2px,color:#111",
)


def node_id(plate: str, label: str) -> str:
    return f"{plate}_{re.sub(r'[^A-Za-z0-9_]', '_', label)}"


def plate_diagram(plate: str, graph: TaskGraph, mandatory: Iterable[str]) -> str:
    """One ``flowchart LR`` per plate: every step is a node, every learned precedence an edge."""
    required = set(mandatory)
    nodes = graph.nodes_of("PT")
    lines = ["flowchart LR"]
    lines += [f'    {node_id(plate, label)}["{label}"]' for label in nodes]
    lines += [
        f"    {node_id(plate, a)} --> {node_id(plate, b)}" for a, b in graph.relation("precedesPT")
    ]
    lines += list(CLASSES)
    plain = [node_id(plate, label) for label in nodes if label not in required]
    marked = [node_id(plate, label) for label in nodes if label in required]
    if plain:
        lines.append(f"    class {','.join(plain)} step")
    if marked:
        lines.append(f"    class {','.join(marked)} mandatory")
    return "\n".join(lines)


def render_sop_knowledge(graphs_dir: Path) -> str:
    graphs, bounds, mandatory = load_knowledge(graphs_dir)
    meta = _meta(graphs_dir)
    out = [
        "# Learned HA-ViD procedure knowledge, drawn",
        "",
        f"Generated by `sop-monitor export-sop-mermaid --graphs {_shown(graphs_dir)}` from the",
        "JSON files the SOP checks read; `tests/test_sop_mermaid.py` fails when this page is stale.",
        "Do not edit by hand.",
        "",
        "Every node is an instruction-sheet step (HR-SAT code with the hole index and tool dropped).",
        "An edge `a --> b` is a learned precedence: `a` starts before `b` in every train recording of",
        f"the plate in which both occur, with at least {meta.get('min_support', '?')} such recordings",
        f"(min agreement {meta.get('min_agreement', '?')}). Orange nodes are mandatory steps (present",
        f"in at least {meta.get('mandatory_fraction', '?')} of the plate's train recordings); an omission",
        "is only ever reported for those. Steps without an edge are still nodes: the order check has",
        "nothing to say about them, which is most of the `general` plate.",
        "",
    ]
    for plate in PLATES:
        graph = graphs[plate]
        nodes = graph.nodes_of("PT")
        edges = graph.relation("precedesPT")
        out += [
            f"## {plate} plate: {len(nodes)} steps, {len(edges)} precedence edges, "
            f"{len(mandatory[plate])} mandatory, {len(bounds[plate])} with duration windows",
            "",
            "```mermaid",
            plate_diagram(plate, graph, mandatory[plate]),
            "```",
            "",
            _bounds_table(bounds[plate], set(mandatory[plate])),
            "",
        ]
    return "\n".join(out).rstrip("\n") + "\n"


def _bounds_table(bounds: Mapping[str, DurationBounds], mandatory: set[str]) -> str:
    lines = ["| step | mandatory | duration window (s) |", "|---|---|---|"]
    for label in sorted(bounds):
        window = bounds[label]
        lines.append(
            f"| `{label}` | {'yes' if label in mandatory else ''} | {window.low:.1f} – {window.high:.1f} |"
        )
    return "\n".join(lines)


def _meta(graphs_dir: Path) -> dict[str, object]:
    import json

    payload = json.loads((graphs_dir / "mandatory_steps.json").read_text(encoding="utf-8"))
    return dict(payload.get("meta", {}))


def _shown(graphs_dir: Path) -> str:
    """The knowledge directory relative to the repository root, however it was passed."""
    root = Path(__file__).resolve().parents[2]
    try:
        return graphs_dir.resolve().relative_to(root).as_posix()
    except ValueError:
        return graphs_dir.as_posix()
